#!/bin/bash

set -euo pipefail

# Build a self-contained PADDL.app and PADDL DMG on macOS.
# Java's jpackage is platform-specific, so this script must be run on a Mac.

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

# Fail early instead of producing a non-runnable cross-platform bundle.
if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "This script must be run on macOS."
    exit 1
fi

PROJECT_VERSION="${PROJECT_VERSION:-1.0-SNAPSHOT}"
APP_VERSION="${APP_VERSION:-1.0.0}"
APP_NAME="PADDL"
MAIN_JAR="CanoeAnalysis-${PROJECT_VERSION}.jar"

# Prefer an explicitly configured JDK, otherwise select the installed Java 21 JDK.
if [[ -z "${JAVA_HOME:-}" ]]; then
    JAVA_HOME="$(/usr/libexec/java_home -v 21)"
fi
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"

# Maven produces the application JAR and copies its runtime dependencies.
if ! command -v mvn >/dev/null 2>&1; then
    echo "Maven is required. Install Maven, then run this script again."
    exit 1
fi

BUILD_DIR="$PROJECT_ROOT/target"
STAGING_DIR="$BUILD_DIR/package-mac-input"
RUNTIME_DIR="$BUILD_DIR/java-runtime-mac"
MAC_DIST_DIR="$PROJECT_ROOT/dist/macos"
APP_BUNDLE="$MAC_DIST_DIR/${APP_NAME}.app"
RESOURCE_SOURCE="$PROJECT_ROOT/src/main/resources/com/wecca/canoeanalysis"
RESOURCE_DESTINATION="$APP_BUNDLE/Contents/Resources"

# Restrict recursive cleanup to directories generated by this script.
safe_remove_generated_directory() {
    local target="$1"
    case "$target" in
        "$PROJECT_ROOT/target/"*|"$PROJECT_ROOT/dist/macos")
            rm -rf -- "$target"
            ;;
        *)
            echo "Refusing to remove unexpected path: $target"
            exit 1
            ;;
    esac
}

echo "Building PADDL ${APP_VERSION} with Java at ${JAVA_HOME}"
mvn -q clean package

# Recreate deterministic staging, runtime, and distribution directories.
safe_remove_generated_directory "$STAGING_DIR"
safe_remove_generated_directory "$RUNTIME_DIR"
safe_remove_generated_directory "$MAC_DIST_DIR"
mkdir -p "$STAGING_DIR" "$MAC_DIST_DIR"

cp "$BUILD_DIR/$MAIN_JAR" "$STAGING_DIR/"
cp "$BUILD_DIR"/libs/*.jar "$STAGING_DIR/"

# Build the smallest self-contained Java runtime needed by PADDL and JavaFX.
"$JAVA_HOME/bin/jlink" \
    --strip-native-commands \
    --no-header-files \
    --no-man-pages \
    --compress=2 \
    --strip-debug \
    --add-modules java.base,jdk.localedata,jdk.unsupported,java.xml,java.scripting,jdk.zipfs,java.rmi,java.naming,java.desktop \
    --include-locales=en \
    --output "$RUNTIME_DIR"

# Create the native .app bundle around the staged JARs and custom runtime.
"$JAVA_HOME/bin/jpackage" \
    --type app-image \
    --dest "$MAC_DIST_DIR" \
    --input "$STAGING_DIR" \
    --name "$APP_NAME" \
    --main-class com.wecca.canoeanalysis.Main \
    --main-jar "$MAIN_JAR" \
    --java-options "-Xmx2048m" \
    --java-options "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED" \
    --java-options "--add-opens=java.base/java.lang=ALL-UNNAMED" \
    --java-options "--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED" \
    --java-options "--add-exports=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED" \
    --java-options "--add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED" \
    --java-options "--add-exports=javafx.base/com.sun.javafx.binding=ALL-UNNAMED" \
    --java-options "--add-exports=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED" \
    --runtime-image "$RUNTIME_DIR" \
    --icon "$RESOURCE_SOURCE/images/canoe.icns" \
    --app-version "$APP_VERSION" \
    --vendor "WECCA" \
    --copyright "Copyright © 2026 WECCA" \
    --mac-package-identifier com.wecca.canoeanalysis \
    --mac-package-name "$APP_NAME"

# Preserve the resources PADDL resolves beside the packaged application bundle.
mkdir -p "$RESOURCE_DESTINATION"
cp -R "$RESOURCE_SOURCE/css" "$RESOURCE_DESTINATION/"
cp -R "$RESOURCE_SOURCE/font" "$RESOURCE_DESTINATION/"
cp -R "$RESOURCE_SOURCE/settings" "$RESOURCE_DESTINATION/"

# Wrap the verified .app image in the distributable disk image requested by README.
"$JAVA_HOME/bin/jpackage" \
    --type dmg \
    --dest "$PROJECT_ROOT/dist" \
    --name "$APP_NAME" \
    --app-image "$APP_BUNDLE" \
    --icon "$RESOURCE_SOURCE/images/canoe.icns" \
    --app-version "$APP_VERSION" \
    --vendor "WECCA" \
    --copyright "Copyright © 2026 WECCA" \
    --mac-package-identifier com.wecca.canoeanalysis \
    --mac-package-name "$APP_NAME"

echo "Created $APP_BUNDLE"
echo "Created $PROJECT_ROOT/dist/${APP_NAME}-${APP_VERSION}.dmg"
